# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='blog_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
