# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20170822_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluded', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Initiated'), (2, 'Success'), (3, 'Failure')])),
                ('payment_type', models.PositiveIntegerField(choices=[(0, 'Donation'), (1, 'Dues')])),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
