# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-09-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
    ]
