# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
