# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-05 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170704_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2017, 7, 5, 19, 37, 21, 499262, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
