# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170805_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='gift',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='names',
        ),
        migrations.AddField(
            model_name='gift',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='gift',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
