# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-22 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170819_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
