# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170822_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Debit Card')], default=1),
        ),
    ]
