# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170822_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gift',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Debit card')], default=1),
        ),
    ]
