# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170825_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gift_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GiftOptions'),
        ),
    ]
