# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gift_gift_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
