# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-26 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170825_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Membership'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='payment_type',
            field=models.PositiveIntegerField(),
        ),
    ]
