# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170826_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='gift_option',
        ),
        migrations.AddField(
            model_name='gift',
            name='currency',
            field=models.PositiveIntegerField(choices=[(0, 'NGN'), (1, 'USD'), (2, 'GBP'), (3, 'EURO')], default=0),
        ),
    ]
