# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170826_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Debit card')], default=0),
        ),
    ]
