# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-31 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_gift_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='currency',
        ),
    ]
