# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-03 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_gift_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
