# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_membership_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
