# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
