# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_activities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
