# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-05 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20170804_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
