# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-01 14:29
from __future__ import unicode_literals

import convention.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0003_studentdelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdelegate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=convention.models.upload_location),
        ),
    ]
